import { ipcMain, dialog, app } from "electron";
import { join, dirname } from "node:path";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { homedir, platform, arch, release } from "node:os";
import { getAuditLog } from "../db";

export function registerExportHandlers(): void {
  ipcMain.handle("export:script", async () => {
    try {
      const openclawDir = join(homedir(), ".openclaw");
      const composePath = join(openclawDir, "docker-compose.yml");
      const envPath = join(openclawDir, ".env");
      
      if (!existsSync(composePath) || !existsSync(envPath)) {
        return { success: false, error: "OpenClaw configuration files not found in ~/.openclaw." };
      }

      // Read current configuration
      const rawEnvContent = readFileSync(envPath, "utf-8");
      
      // Mask secrets in .env
      const envContent = rawEnvContent
        .split("\\n")
        .map(line => {
          if (line.trim().startsWith("#") || !line.includes("=")) return line;
          const [key, ...rest] = line.split("=");
          const val = rest.join("=");
          if (key.includes("KEY") || key.includes("TOKEN") || key.includes("SECRET") || key.includes("PASSWORD")) {
            return `${key}=******** (Hidden for security) ********`;
          }
          return line;
        })
        .join("\\n");
        
      const composeContent = readFileSync(composePath, "utf-8");
      
      // Try to read openclaw.json if it exists
      let jsonContent = "";
      const jsonPath = join(openclawDir, "openclaw.json");
      if (existsSync(jsonPath)) {
        const rawJson = readFileSync(jsonPath, "utf-8");
        try {
            const parsed = JSON.parse(rawJson);
            // Mask gateway token
            if (parsed.gateway?.auth?.token) {
                parsed.gateway.auth.token = "******** (Hidden for security) ********";
            }
            // Mask channel tokens
            if (parsed.channels?.telegram?.botToken) {
                parsed.channels.telegram.botToken = "******** (Hidden for security) ********";
            }
            if (parsed.channels?.discord?.token) {
                parsed.channels.discord.token = "******** (Hidden for security) ********";
            }
            jsonContent = JSON.stringify(parsed, null, 2);
        } catch {
            jsonContent = rawJson; // fallback if invalid JSON
        }
      }

      // Prepare the bash script content
      const scriptContent = `#!/bin/bash
# OpenClaw Auto-Generated Deployment Script
# Generated by OpenClaw Control Center
# https://github.com/openclaw/openclaw

set -e

# Colors for output
GREEN='\\033[0;32m'
BLUE='\\033[0;34m'
YELLOW='\\033[1;33m'
RED='\\033[0;31m'
NC='\\033[0m' # No Color

echo -e "\${BLUE}============== OpenClaw Deployment ==============\${NC}"
echo -e "\${YELLOW}Preparing to deploy OpenClaw...\${NC}"

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo -e "\${RED}Error: Docker is not installed or not in PATH.\${NC}"
    echo "Please install Docker and try again."
    exit 1
fi

# Check for Docker Compose
if ! docker compose version &> /dev/null && ! docker-compose version &> /dev/null; then
    echo -e "\${RED}Error: Docker Compose is not installed.\${NC}"
    echo "Please install Docker Compose and try again."
    exit 1
fi

COMPOSE_CMD="docker compose"
if ! docker compose version &> /dev/null; then
    COMPOSE_CMD="docker-compose"
fi

INSTALL_DIR="$HOME/.openclaw"
echo -e "\${BLUE}Creating directory \${INSTALL_DIR}...\${NC}"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

echo -e "\${BLUE}Writing configuration files...\${NC}"

# Write .env file
cat << 'EOF' > .env
${envContent}
EOF

# Write docker-compose.yml file
cat << 'EOF' > docker-compose.yml
${composeContent}
EOF

${
  jsonContent ? `
# Write openclaw.json file
cat << 'EOF' > openclaw.json
${jsonContent}
EOF
` : ""
}

echo -e "\${BLUE}Setting permissions...\${NC}"
chmod 600 .env
if [ -f "openclaw.json" ]; then
    chmod 644 openclaw.json
fi

echo -e "\${YELLOW}Starting OpenClaw containers...\${NC}"
$COMPOSE_CMD pull
$COMPOSE_CMD up -d

echo -e "\${GREEN}============== Deployment Complete ==============\${NC}"
echo -e "OpenClaw is now running in the background."
echo -e "Use '\${COMPOSE_CMD} logs -f' in \${INSTALL_DIR} to view logs."
`;

      // Ask user where to save the script
      const { canceled, filePath } = await dialog.showSaveDialog({
        title: "Export Deployment Script",
        defaultPath: "deploy-openclaw.sh",
        filters: [
          { name: "Bash Script", extensions: ["sh"] },
          { name: "All Files", extensions: ["*"] }
        ]
      });

      if (canceled || !filePath) {
        return { success: false, error: "Export canceled by user." };
      }

      // Write the file
      writeFileSync(filePath, scriptContent, "utf-8");

      return { success: true, filePath };
    } catch (error) {
      console.error("Export script error:", error);
      return { 
        success: false, 
        error: error instanceof Error ? error.message : "Unknown error exporting script" 
      };
    }
  });

  // Epic 7 (Ampliación): Export de Diagnóstico Mejorado
  ipcMain.handle("diagnostic:export", async () => {
    try {
      const openclawDir = join(homedir(), ".openclaw");
      const auditLogs = getAuditLog(50);
      
      const diagnosticData = {
        timestamp: new Date().toISOString(),
        appVersion: app.getVersion(),
        platform: {
          os: platform(),
          arch: arch(),
          release: release(),
        },
        openclaw: {
          installed: existsSync(join(openclawDir, "docker-compose.yml")),
          configExists: existsSync(join(openclawDir, ".env")),
        },
        auditLog: auditLogs.map(log => ({
          ...log,
          // Ensure details are safe (already handled in handlers, but double check)
          detail: log.detail?.replace(/(KEY|TOKEN|SECRET|PASSWORD)=[^\\s]+/gi, "$1=********") || null
        }))
      };

      const { canceled, filePath } = await dialog.showSaveDialog({
        title: "Export Diagnostic Report",
        defaultPath: `openclaw-diagnostic-\${new Date().getTime()}.json`,
        filters: [
          { name: "JSON Report", extensions: ["json"] },
          { name: "All Files", extensions: ["*"] }
        ]
      });

      if (canceled || !filePath) {
        return { success: false, message: "Export canceled" };
      }

      writeFileSync(filePath, JSON.stringify(diagnosticData, null, 2), "utf-8");
      logAction("diagnostic:export", `path=\${filePath}`, "success");
      
      return { success: true, message: `Diagnóstico exportado a \${filePath}` };
    } catch (error) {
      console.error("Diagnostic export error:", error);
      return { success: false, message: String(error) };
    }
  });
}

/**
 * Internal helper to log actions (proxied from db to avoid circular deps if any, 
 * although db doesn't import export.handler)
 */
function logAction(action: string, detail: string, result: string) {
  try {
    const { logAction: dbLog } = require("../db");
    dbLog(action, detail, result);
  } catch {}
}

